### ISSUE TITLE
CTP mini  运行后填入用户名密码后，一直报行情服务器连接断开，原因-3 ，是填的地址有问题吗？如果是的话，应该填什么地址？

### ISSUE THREAD

**Issue by longshared** [vnpy/vnpy_mini#11]
CTP mini  运行后填入用户名密码后，一直报行情服务器连接断开，原因-3 ，是填的地址有问题吗？如果是的话，应该填什么地址？
在CTP中登录是正常的，只是在CTP mini中有问题
![877e9a290aadb272330b9ea4155a2b6](https://user-images.githubusercontent.com/16349572/217422307-5fcecb8a-445d-4f8f-94cf-aa246225dac3.png)
![b32b70942d31fc1161a6f95415f291d](https://user-images.githubusercontent.com/16349572/217422336-7dbd6b46-ef17-411b-9f08-45200c89dd7f.png)

期望回复，顺祝商祺

**Comment by vnpy** [comment]
CTP Mini是和CTP不同的极速柜台，因此需要使用专门的服务器地址，通常期货公司会有提供CTP Mini的测试环境服务器，SimNow是没有的。
